# Generated by Django 5.0 on 2023-12-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(default='this-is-first-news'),
            preserve_default=False,
        ),
    ]
