# Generated by Django 5.0 on 2023-12-15 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='body',
            new_name='asosoiy_matn',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='image',
            new_name='rasm',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='title',
            new_name='sarlavha',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='subtitle',
            new_name='taglavha',
        ),
    ]
